import { Tektur } from "next/font/google";
import "./globals.css";

// Configura la fuente Tektur
const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"], // Especifica los pesos que necesitas
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tektur.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
